### ISSUE TITLE
Exception for corrupted data

### ISSUE THREAD

**Issue by bobby68** [salmonthinlion/YahooFinanceApi#3]
Unfortunately some of the data seems to got corrupted by Yahoo.  If I download CSV file manually using the browser, corrupted data lines show as "yyyy-MM-dd,null,null,null,null,null,nulll", and they cause the formatting exceptions and failure in YahooFinanceApi. For example, this happened to me with symbols VAW and FSESX. Could it be possible to just place nulls in the affected list entries, to mimic the manual download?

**Comment by salmonthinlion** [comment]
Since the corrupted data lines are not usable and do not contains any information, i have added codes to skip all these corrupted lines in the commit, please see if the library works again, thanks.

**Comment by bobby68** [comment]
Works well, thank you for a quick response.
